services:
  frontend:
    build:
      context: .
      dockerfile: docker/frontend.Dockerfile
    container_name: frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    env_file:
      - .env 
    networks:
      - liftnote

  backend:
    build:
      context: .
      dockerfile: docker/backend.Dockerfile
    container_name: backend
    ports:
      - "8000:80"
    depends_on:
      - liftnote_db
    volumes:
      - ./backend:/var/www/html
    env_file:
      - ./backend/.env
    command: ["sh", "-c", "apache2-foreground"]
    networks:
      - liftnote

  liftnote_db:
    image: mysql:8.0
    container_name: liftnote_db
    ports:
      - "3309:3306"
    env_file:
      - .env
    volumes:
      - liftnote_db_data:/var/lib/mysql
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    command: --default-authentication-plugin=mysql_native_password --bind-address=0.0.0.0
    networks:
      - liftnote

volumes:
  liftnote_db_data:

networks:
  liftnote:
    driver: bridge