services:
  frontend:
    build:
      context: .
      dockerfile: docker/frontend.Dockerfile
    container_name: frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    command: npm run dev
    depends_on:
      - backend
    env_file:
      - .env 
    networks:
      - liftnote

  backend:
    build:
      context: .
      dockerfile: docker/backend.Dockerfile
    container_name: backend
    ports:
      - "8000:80"
    depends_on:
      - liftnote_db
    volumes:
      - ./backend:/var/www/html
    env_file:
      - ./backend/.env
    command: ["sh", "-c", "apache2-foreground"]
    networks:
      - liftnote

  mobile:
    build:
      context: .
      dockerfile: docker/mobile.Dockerfile
    container_name: mobile
    ports:
      - "19000:19000"  # Expo dev server
      - "19001:19001"  # Expo dev tools
      - "19002:19002"  # Expo web
    volumes:
      - ./mobile:/app
      - /app/node_modules
    environment:
      - EXPO_DEVTOOLS_LISTEN_ADDRESS=0.0.0.0
      - REACT_NATIVE_PACKAGER_HOSTNAME=localhost
    depends_on:
      - backend
    networks:
      - liftnote

  liftnote_db:
    image: mysql:8.0
    container_name: liftnote_db
    ports:
      - "3309:3306"
    env_file:
      - .env
    volumes:
      - liftnote_db_data:/var/lib/mysql
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    command: --default-authentication-plugin=mysql_native_password --bind-address=0.0.0.0
    networks:
      - liftnote
    restart: always

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - "8092:80"
    environment:
      PMA_HOST: liftnote_db
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    depends_on:
      - liftnote_db
    networks:
      - liftnote

  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    restart: always
    ports:
      - "8042:8025"
      - "1042:1025"
    networks:
      - liftnote

volumes:
  liftnote_db_data:

networks:
  liftnote:
    driver: bridge
