name: Test Secrets

on:
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/test-secrets.yml']

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Test Secrets
      run: |
        echo "Testing GitHub secrets access..."
        echo "DROPLET_HOST length: ${#DROPLET_HOST}"
        echo "DROPLET_USERNAME length: ${#DROPLET_USERNAME}"
        echo "DROPLET_SSH_KEY length: ${#DROPLET_SSH_KEY}"
        echo "DROPLET_PORT length: ${#DROPLET_PORT}"
        
        if [ -n "$DROPLET_HOST" ]; then
          echo "✅ DROPLET_HOST is set"
        else
          echo "❌ DROPLET_HOST is not set"
        fi
        
        if [ -n "$DROPLET_USERNAME" ]; then
          echo "✅ DROPLET_USERNAME is set"
        else
          echo "❌ DROPLET_USERNAME is not set"
        fi
        
        if [ -n "$DROPLET_SSH_KEY" ]; then
          echo "✅ DROPLET_SSH_KEY is set"
        else
          echo "❌ DROPLET_SSH_KEY is not set"
        fi
        
        if [ -n "$DROPLET_PORT" ]; then
          echo "✅ DROPLET_PORT is set"
        else
          echo "❌ DROPLET_PORT is not set"
        fi
      env:
        DROPLET_HOST: ${{ secrets.DROPLET_HOST }}
        DROPLET_USERNAME: ${{ secrets.DROPLET_USERNAME }}
        DROPLET_SSH_KEY: ${{ secrets.DROPLET_SSH_KEY }}
        DROPLET_PORT: ${{ secrets.DROPLET_PORT }} 